#!/usr/bin/env bash

function err() {
	echo $* >&2
	exit 1
}

function name2id() {
	echo $* | sed -E -e 's/ /_/g' -e 's/_{2,}/_/g' -e 's/_+$//g'
}

function readx() {
	declare -n _readx="$2"
	read -rp "$1" _readx
	[ -z "$_readx" ] && _readx="$3"
}

function yaml2json() {
	python3 - "$1" <<EOF
import yaml
import json
import sys

with open(sys.argv[1]) as f:
    print(json.dumps(yaml.safe_load(f)))
EOF
}

case "$1" in
new-author)
	readx "What's the name of the author: " name
	id=$(name2id $name)
	readx "What's the ID of the author [$id]: " id $id

	[ -f "authors/$id.yaml" ] && err "File already exist: authors/$id.yaml"

	avatar=$id.jpg
	readx "What's the avatar file name of the author [$avatar]: " avatar $avatar
	type=""

	echo "Select the type of the author: "
	select x in $(yaml2json schemas/author.schema.yaml | jq -r '.properties.type.enum | join(" ")') ; do
		typename=$x
		break
	done

	tee "authors/$id.yaml" <<EOF
# Generated by dbutils.sh
# remove these comment after you acknowledged/edited it

name: $name

type: $typename

avatar: $avatar

#, fuzzy
links:
  - name: STUB
    uri: /_stub
EOF
	;;
*)
	echo Unknown command $1
	exit 1
	;;
esac
