name: pr-build-check

on:
  pull_request:
    branches: [ master ]

env:
  ID: ${{ github.event.pull_request.head.label }}
  SHA_ID: ${{ github.event.pull_request.head.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
        submodules: true

    - name: install-dep
      run: |
        sudo apt -y update || true
        sudo apt -y install git python3 python3-yaml python3-jinja2 python3-pip python3-setuptools python3-pil python3-bs4 python3-jsonschema webp
        pip3 install --user git+https://github.com/FurryGamesIndex/python-markdown2

    - name: lint
      env:
        BASE_REF: ${{ github.event.pull_request.base.sha }}
      run: |
        IFS=$'\n'
        dfs="$(git diff --name-only --diff-filter=AMR "$BASE_REF")"

        echo "$dfs" | grep '^games/[^/]*$' | while read -r i; do
          ./scripts/lint.sh game "$i"
        done
        echo "$dfs" | grep '^games/l10n/[^/]*$' | while read -r i; do
          ./scripts/lint.sh game-l10n "$i"
        done

    - name: gen
      run: |
        python3 --version
        ./generate.py \
            --no-sub-lists \
            --no-sitemap \
            --file-uri-workaround \
            --images-to-webp \
            --plugin steam-cdn-unite,verbose=1 \
            output

    - name: tarball
      run: |
        cd output
        tar cvf "../build.tar" .

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.SHA_ID }}
        path: build.tar
